CFLAGS += -DSTM32F10X_MD
CFLAGS += -DUSE_STDPERIPH_DRIVER

CFLAGS += \
	-ILibraries/STM32F10x_StdPeriph_Driver/inc \
	-ILibraries/CMSIS/CM3/DeviceSupport/ST/STM32F10x \
	-ILibraries/CMSIS/CM3/CoreSupport

OBJS += \
	Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.o \
	Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.o \
	Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.o \
	Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.o \
	Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.o \
	Libraries/STM32F10x_StdPeriph_Driver/src/misc.o \
	Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.o
